### ISSUE TITLE
pip install is not working

### ISSUE THREAD

**Issue by mwmattis** [drlukeparry/libSLM#6]
Hi @drlukeparry.

I wanted to test your library in python by cloning + running **pip install .\libSLM** but unfortunately I get an error:

    CMake Error at CMakeLists.txt:139 (add_subdirectory):
      add_subdirectory given source "Translators" which is not an existing
      directory.

The directory seems to be missing in the repository.

Best regards,
Mattis

**Comment by drlukeparry** [comment]
Hi Mattis,

This is intentional because this folder contains the translators used for reading & writing to the specific commercial SLMS machine that for now is kept in a private repository for academic/research purposes only. Without these, the library will not provide much benefit. In future, I will most likely include a reference to the .cli file format for everyone to compile the library.

If you would like to compile and/or use the libSLM library please send a message to dev@lukeparry.uk

Kind Wishes,
Luke
